# ===================================================================
# Configuracion de Logs
# ===================================================================

spring.application.name=invex-employee-service

# 1. NIVELES DE LOG
# -------------------------------------------------------------------
# Define el nivel de log por defecto para toda la aplicación.
# Niveles comunes (de menos a más detallado): ERROR, WARN, INFO, DEBUG, TRACE
logging.level.root=INFO

# Define un nivel más detallado solo para los paquetes de tu proyecto.
# Esto es muy útil para ver tus propios logs en DEBUG sin el ruido de las librerías externas.
logging.level.com.invex.employee=DEBUG

# Útil para depurar problemas de base de datos. Muestra las consultas SQL que ejecuta Hibernate.
logging.level.org.hibernate.SQL=DEBUG
# Muestra los parámetros que se usan en las consultas SQL de Hibernate (complementa al anterior).
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# 2. SALIDA DE LOGS A ARCHIVO
# -------------------------------------------------------------------
# Especifica el nombre y la ruta del archivo donde se guardarán los logs.
logging.file.name=logs/invex-employee-service.log

# Configura la rotación de archivos. Cuando el log llegue a 10MB, se creará uno nuevo.
logging.logback.rollingpolicy.max-file-size=10MB

# Define cuántos archivos de log históricos se conservarán.
logging.logback.rollingpolicy.max-history=7

# 3. FORMATO DE LOS MENSAJES (PATRÓN)
# -------------------------------------------------------------------
# Personaliza cómo se ven los logs en la consola.
# %d: fecha y hora, %thread: hilo de ejecución, %-5level: nivel de log, %logger{36}: nombre del logger, %msg%n: mensaje y salto de línea.
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Personaliza el formato para el archivo de log (puede ser diferente al de la consola).
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
